/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#22c55e',
        'surface-container-high': '#e6e8ea',
        tertiary: '#003211',
        'on-primary-fixed': '#00164e',
        error: '#ba1a1a',
        'primary-fixed': '#dce1ff',
        'error-container': '#ffdad6',
        background: '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#eceef0',
        'secondary-fixed': '#89f5e7',
        'surface-variant': '#e0e3e5',
        'on-error': '#ffffff',
        outline: '#757682',
        'on-primary-container': '#90a8ff',
        'surface-container-low': '#f2f4f6',
        'inverse-on-surface': '#eff1f3',
        'on-secondary-fixed': '#00201d',
        'tertiary-container': '#004b1e',
        'tertiary-fixed': '#6bff8f',
        'primary-fixed-dim': '#b6c4ff',
        'on-surface-variant': '#444651',
        'on-primary-fixed-variant': '#264191',
        'on-primary': '#ffffff',
        'surface-tint': '#4059aa',
        'surface-bright': '#f7f9fb',
        'on-background': '#191c1e',
        'on-surface': '#191c1e',
        'on-error-container': '#93000a',
        'on-secondary': '#ffffff',
        'inverse-primary': '#b6c4ff',
        surface: '#f7f9fb',
        'on-secondary-container': '#006f66',
        'surface-dim': '#d8dadc',
        'primary-container': '#1e3a8a',
        primary: '#00236f',
        'tertiary-fixed-dim': '#4ae176',
        'outline-variant': '#c5c5d3',
        'secondary-container': '#86f2e4',
        secondary: '#006a61',
        'inverse-surface': '#2d3133',
        'secondary-fixed-dim': '#6bd8cb',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#005049',
        'on-tertiary-fixed': '#002109',
        'surface-container-highest': '#e0e3e5',
        'on-tertiary-fixed-variant': '#005321',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
        headline: ['Sora', 'Plus Jakarta Sans', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
        label: ['Plus Jakarta Sans', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

